### ISSUE TITLE
sf hardis:scratch:create generates a really long user name, but the limit is 80 chars

### ISSUE THREAD

**Issue by marcoalmodova** [hardisgroupcom/sfdx-hardis#887]
Error log:

Assertion failed: [sfdx-hardis] Error creating scratch org. Maybe try sf hardis:scratch:create --forcenew ?
{
  "status": 1,
  "errorMessage": "[sfdx-hardis][ERROR] Error processing command\n${\n  \"name\": \"STRING_TOO_LONG\",\n  \"message\": \"Requested Username: data value too large: marco.almodova@hardis-scratch-ci-marco.almodova-feature__test-c_20241115_0451.com (max length=80)\",\n  \"exitCode\": 1,\n  \"context\": \"OrgCreateScratch\",\n  \"stack\": \"STRING_TOO_LONG: Requested Username: data value too large: marco.almodova@hardis-scratch-ci-marco.almodova-feature__test-c_20241115_0451.com (max length=80)\\n    at SfCommandError.from (file:///Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@salesforce/sf-plugins-core/lib/SfCommandError.js:39:16)\\n    at OrgCreateScratch.catch (file:///Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@salesforce/sf-plugins-core/lib/sfCommand.js:316:47)\\n    at OrgCreateScratch._run (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/command.js:306:29)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async Config.runCommand (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/config/config.js:425:25)\\n    at async run (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/main.js:95:16)\\n    at async file:///Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/bin/run.js:15:1\",\n  \"cause\": \"STRING_TOO_LONG: Requested Username: data value too large: marco.almodova@hardis-scratch-ci-marco.almodova-feature__test-c_20241115_0451.com (max length=80)\\n    at HttpApi.getError (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@jsforce/jsforce-node/lib/http-api.js:290:56)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async /Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@jsforce/jsforce-node/lib/http-api.js:127:33\\n    at async Connection.create (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@jsforce/jsforce-node/lib/connection.js:733:15)\\n    at async requestScratchOrgCreation (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@salesforce/core/lib/org/scratchOrgInfoApi.js:283:16)\\n    at async Promise.all (index 0)\\n    at async scratchOrgCreate (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:148:65)\\n    at async OrgCreateScratch.run (file:///Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@salesforce/plugin-org/lib/commands/org/create/scratch.js:195:72)\\n    at async OrgCreateScratch._run (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/command.js:302:22)\\n    at async Config.runCommand (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/config/config.js:425:25)\\n    at async run (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/main.js:95:16)\\n    at async file:///Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/bin/run.js:15:1 {\\n  data: {\\n    message: 'Requested Username: data value too large: marco.almodova@hardis-scratch-ci-marco.almodova-feature__test-c_20241115_0451.com (max length=80)',\\n    errorCode: 'STRING_TOO_LONG',\\n    fields: [ 'Username' ]\\n  },\\n  errorCode: 'STRING_TOO_LONG'\\n}\",\n  \"warnings\": [],\n  \"code\": \"STRING_TOO_LONG\",\n  \"status\": 1,\n  \"commandName\": \"OrgCreateScratch\"\n}\n\n",
  "error": {
    "code": 1,
    "killed": false,
    "signal": null,
    "cmd": "sf org create scratch --set-default --definition-file ./config/user/project-scratch-def-CI-marco.almodova-feature__test-c_20241115_0451.json --alias CI-marco.almodova-feature__test-c_20241115_0451 --wait 15 --target-dev-hub DevHub_testHardis --duration-days 1 --json",
    "stdout": "{\n  \"name\": \"STRING_TOO_LONG\",\n  \"message\": \"Requested Username: data value too large: marco.almodova@hardis-scratch-ci-marco.almodova-feature__test-c_20241115_0451.com (max length=80)\",\n  \"exitCode\": 1,\n  \"context\": \"OrgCreateScratch\",\n  \"stack\": \"STRING_TOO_LONG: Requested Username: data value too large: marco.almodova@hardis-scratch-ci-marco.almodova-feature__test-c_20241115_0451.com (max length=80)\\n    at SfCommandError.from (file:///Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@salesforce/sf-plugins-core/lib/SfCommandError.js:39:16)\\n    at OrgCreateScratch.catch (file:///Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@salesforce/sf-plugins-core/lib/sfCommand.js:316:47)\\n    at OrgCreateScratch._run (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/command.js:306:29)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async Config.runCommand (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/config/config.js:425:25)\\n    at async run (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/main.js:95:16)\\n    at async file:///Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/bin/run.js:15:1\",\n  \"cause\": \"STRING_TOO_LONG: Requested Username: data value too large: marco.almodova@hardis-scratch-ci-marco.almodova-feature__test-c_20241115_0451.com (max length=80)\\n    at HttpApi.getError (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@jsforce/jsforce-node/lib/http-api.js:290:56)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async /Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@jsforce/jsforce-node/lib/http-api.js:127:33\\n    at async Connection.create (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@jsforce/jsforce-node/lib/connection.js:733:15)\\n    at async requestScratchOrgCreation (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@salesforce/core/lib/org/scratchOrgInfoApi.js:283:16)\\n    at async Promise.all (index 0)\\n    at async scratchOrgCreate (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:148:65)\\n    at async OrgCreateScratch.run (file:///Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@salesforce/plugin-org/lib/commands/org/create/scratch.js:195:72)\\n    at async OrgCreateScratch._run (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/command.js:302:22)\\n    at async Config.runCommand (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/config/config.js:425:25)\\n    at async run (/Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/node_modules/@oclif/core/lib/main.js:95:16)\\n    at async file:///Users/marco.almodova/.local/share/sf/client/2.65.8-23a374a/bin/run.js:15:1 {\\n  data: {\\n    message: 'Requested Username: data value too large: marco.almodova@hardis-scratch-ci-marco.almodova-feature__test-c_20241115_0451.com (max length=80)',\\n    errorCode: 'STRING_TOO_LONG',\\n    fields: [ 'Username' ]\\n  },\\n  errorCode: 'STRING_TOO_LONG'\\n}\",\n  \"warnings\": [],\n  \"code\": \"STRING_TOO_LONG\",\n  \"status\": 1,\n  \"commandName\": \"OrgCreateScratch\"\n}\n",
    "stderr": ""
  }
}
Error (10): Cannot read properties of undefined (reading 'username')

**Comment by marcoalmodova** [comment]
The feature branch was named as feature/ci-test, which is a short name actually.
